# # cat docker-compose.yml
# version: '3.8'
# services:
# ### MySQL Container
#   mysql:
#     build:
#       args:
#         - MYSQL_DATABASE=dacn2
#         - MYSQL_ROOT_PASSWORD=root
#     ports:
#       - "3306:3306"
#     volumes:
#     - ./dump:/docker-entrypoint-initdb.d



version: '3.8'
services:
  db:
    image: mysql:8.0
    # them vao
    container_name: db_dacn2
    build:
      context: .
      dockerfile: db.Dockerfile
    # end them vao
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dacn2
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      dacn2:
        ipv4_address: 172.26.0.2

  api_go:
    container_name: api_go_dacn2
    build:
      context: .
      dockerfile: api_go.Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      dacn2:
        ipv4_address: 172.26.0.3
    depends_on:
      - "db"
  
  api_node:
    container_name: api_node_dacn2
    build:
      context: .
      dockerfile: api_node.Dockerfile
    restart: on-failure
    ports:
      - 9090:9090
    networks:
      dacn2:
        ipv4_address: 172.26.0.4
    depends_on:
      - "db"


volumes:
  db:
    driver: local
networks:
  dacn2:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
    external: true